/*! \file ids.h
    \brief String identificators enumeration.
*/

#ifndef __IDS_H
#define __IDS_H

#define  IDS_MAINMENU         1
#define  IDS_PATIENT          2
#define  IDS_NORM             3
#define  IDS_DOZECALC         4
#define  IDS_DISPLAY          5
#define  IDS_EVENT_LOGS       6
#define  IDS_TRENDS           7
#define  IDS_TABLE            8
#define  IDS_MANUALLY         9
#define  IDS_SETTINGS         10
#define  IDS_QUIT             11
#define  IDS_mIN              12
#define  IDS_OK               13
#define  IDS_DATETIME         14
#define  IDS_LANGUAGE         15
#define  IDS_BRIGHTNESS       16
#define  IDS_SELMODULES       17
#define  IDS_SETDEFAULTS      18
#define  IDS_SUPPORT          19
#define  IDS_DEMO             20
#define  IDS_STEP             21
#define  IDS_NETWORK          22
#define  IDS_NONE             23
#define  IDS_SPACE            24
#define  IDS_AGEGROUP         25
#define  IDS_BEDNO            26
#define  IDS_CARDNO           27
#define  IDS_NUM              28
#define  IDS_HEIGHT_CM        29
#define  IDS_WEIGHT_KG        30
#define  IDS_NEWPATIENT       31
#define  IDS_ATTENTION        32
#define  IDS_SELECT_NEW_PATIENT_1           33
#define  IDS_SELECT_NEW_PATIENT_2           34
#define  IDS_TRENDS_WILL_BE_DELETED_1       35
#define  IDS_TRENDS_WILL_BE_DELETED_2       36
#define  IDS_YES              37
#define  IDS_NO               38
#define  IDS_ALARMS           39
#define  IDS_PHYSIOLOGICAL    40
#define  IDS_aLARMS           41
#define  IDS_TECHNICAL        42
#define  IDS_PRINT_ALL_ALARMS 43
#define  IDS_ALARMS_RANGES_ON_DISP_1        44
#define  IDS_ALARMS_RANGES_ON_DISP_2        45
#define  IDS_VOLUME_OF_ALARMS_1             46
#define  IDS_VOLUME_OF_ALARMS_2             47
#define  IDS_ALARMS_DELAY     48
#define  IDS_DISPCONFIG       49
#define  IDS_ENLARGED         50
#define  IDS_STANDARD         51
#define  IDS_TRENDSET         52
#define  IDS_HR               53
#define  IDS_NIBP             54
#define  IDS_SPO2             55
#define  IDS_PULSE            56
#define  IDS_ST_I             57
#define  IDS_ST_II            58
#define  IDS_ST_III           59
#define  IDS_ST_AVR           60
#define  IDS_ST_AVL           61
#define  IDS_ST_AVF           62
#define  IDS_ST_V             63
#define  IDS_T1               64
#define  IDS_T2               65
#define  IDS_DT               66
#define  IDS_BR               67
#define  IDS_TABLESET         68
#define  IDS_1                69
#define  IDS_2                70
#define  IDS_3                71
#define  IDS_4                72
#define  IDS_5                73
#define  IDS_6                74
#define  IDS_7                75
#define  IDS_8                76
#define  IDS_9                77
#define  IDS_10               78
#define  IDS_11               79
#define  IDS_12               80
#define  IDS_13               81
#define  IDS_14               82
#define  IDS_15               83
#define  IDS_DEFAULT          84
#define  IDS_PRINTSET         85
#define  IDS_NUM_OF_CURVES    86
#define  IDS_CURVE1           87
#define  IDS_CURVE2           88
#define  IDS_PRINTSPEED       89
#define  IDS_PRINTGRID        90
#define  IDS_PRINTVAL         91
#define  IDS_THICKN           92
#define  IDS_BRIGHTN          93
#define  IDS_INT_BETW_CURVES  94
#define  IDS_BEF_START        95
#define  IDS_AFT_START        96
#define  IDS_DAY              97
#define  IDS_MONTH            98
#define  IDS_YEAR             99
#define  IDS_HOUR             100
#define  IDS_MIN              101
#define  IDS_SEC              102
#define  IDS_SET              103
#define  IDS_RUSSIAN_LANG     104
#define  IDS_ENGLISH_LANG     105
#define  IDS_03_LANG          106
#define  IDS_04_LANG          107
#define  IDS_05_LANG          108
#define  IDS_06_LANG          109
#define  IDS_07_LANG          110
#define  IDS_08_LANG          111
#define  IDS_09_LANG          112
#define  IDS_10_LANG          113
#define  IDS_11_LANG          114
#define  IDS_12_LANG          115
#define  IDS_ECG              116
#define  IDS_ID1              117
#define  IDS_CO2              118
#define  IDS_ID2              119
#define  IDS_RESP             120
#define  IDS_T                121
#define  IDS_SAVE             122
#define  IDS_DEFAULT_SETTINGS 123
#define  IDS_SET_DEF_SET_1    124
#define  IDS_SET_DEF_SET_2    125
#define  IDS_DEMOSET          126
#define  IDS_CURR_MODE        127
#define  IDS_DEL_ALL_FILES    128
#define  IDS_DEVICE           129
#define  IDS_POWEROFF_MONI    130
#define  IDS_POWEROFF_MONI_QUERY_1   131
#define  IDS_POWEROFF_MONI_QUERY_2   132
#define  IDS_BEDMONI_UPDATE   133
#define  IDS_SW_VERSION       134
#define  IDS_UPDATING         135
#define  IDS_DO_NOT_POWEROFF  136
#define  IDS_FROM_LOCAL       137
#define  IDS_SERVER_IP        138
#define  IDS_UPDATE           139
#define  IDS_T1T2SET          140
#define  IDS_T1_ALARM         141
#define  IDS_T2_ALARM         142
#define  IDS_DT_ALARM         143
#define  IDS_PRINT_ALARM      144
#define  IDS_RESPSET          145
#define  IDS_RESPALR          146
#define  IDS_ALR_APNOEA       147
#define  IDS_RPG_DATA_ON      148
#define  IDS_RPG_DATA_DRAW    149
#define  IDS_UNUSED_001       150
#define  IDS_UNUSED_002       151
#define  IDS_RPG_LEAD         152
#define  IDS_NIBPSET          153
#define  IDS_NIBPALR          154
#define  IDS_NIBP_SS          155
#define  IDS_NIBP_DD          156
#define  IDS_NIBP_CC          157
#define  IDS_NIBP_INTL_1      158
#define  IDS_NIBP_INTL_2      159
#define  IDS_NIBP_INFL_1      160
#define  IDS_NIBP_INFL_2      161
#define  IDS_CAL              162
#define  IDS_VERIF            163
#define  IDS_LEAK             164
#define  IDS_SPO2SET          165
#define  IDS_SPO2ALR          166
#define  IDS_SPO2_PULSEALR    167
#define  IDS_SPO2_DRAW        168
#define  IDS_ECGSET           169
#define  IDS_ECG_HRALR        170
#define  IDS_NUM_CHANS        171
#define  IDS_HR_SOURCE        172
#define  IDS_DHF              173
#define  IDS_PACEMAKER        174
#define  IDS_ST_MEAS          175
#define  IDS_ST_ANAL          176
#define  IDS_ST_ALR           177
#define  IDS_ARRH_ANAL        178
#define  IDS_ASYSTOLIA        179
#define  IDS_NO_ANSWER        180
#define  IDS_TACHYCARDIA      181
#define  IDS_ST               182
#define  IDS_DEPR             183
#define  IDS_ELEV             184
#define  IDS_ALL_ST_ALARMS    185
#define  IDS_NETWORKSET       186
#define  IDS_IP_ADDR_DEV_1    187
#define  IDS_IP_ADDR_DEV_2    188
#define  IDS_IP_ADDR_HOST_1   189
#define  IDS_IP_ADDR_HOST_2   190
#define  IDS_PORT_HOST        191
#define  IDS_NIBP_CAL         192
#define  IDS_SET_0_MMHG       193
#define  IDS_SET_250_MMHG     194
#define  IDS_INPUT_PASS       195
#define  IDS_ENTER_4_NUMS     196
#define  IDS_AND_PRESS_OK     197
#define  IDS_00               198
#define  IDS_15_MINS_2_WORK_1 199
#define  IDS_15_MINS_2_WORK_2 200
#define  IDS_FPG              201
#define  IDS_RPG              202
#define  IDS_MMPS             203
#define  IDS_AUTO             204
#define  IDS_DIAGNOSTICS      205
#define  IDS_MONITORING       206
#define  IDS_SURGERY          207
#define  IDS_PRINT            208
#define  IDS_BRIEF            209
#define  IDS_DETAILED         210
#define  IDS_ADULT            211
#define  IDS_CHILD            212
#define  IDS_NEONATE          213
#define  IDS_DEMO_LARGE       214
#define  IDS_UNDEF3           215
#define  IDS_UNDEF7           216
#define  IDS_STOPPED          217
#define  IDS_START            218
#define  IDS_CURRENT_CUFF     219
#define  IDS_PRESS_START_1    220
#define  IDS_PRESS_START_2    221
#define  IDS_NIBP_SS_BRF      222
#define  IDS_NIBP_DD_BRF      223
#define  IDS_NIBP_CC_BRF      224
#define  IDS_NIBP_MEAS_TIME   225
#define  IDS_HBPM             226
#define  IDS_MV               227
#define  IDS_MM_HG            228
#define  IDS_BRPM             229
#define  IDS_MMPMV            230
#define  IDS_DATE_OF_PRINT    231
#define  IDS_I                232
#define  IDS_II               233
#define  IDS_III              234
#define  IDS_AVF              235
#define  IDS_AVR              236
#define  IDS_AVL              237
#define  IDS_V                238
#define  IDS_ECG_NEO          239
#define  IDS_sEC              240
#define  IDS_RECORD           241
#define  IDS_STOP             242
#define  IDS_UNABLE_CONNECT   243
#define  IDS_ON               244
#define  IDS_OFF              245
#define  IDS_ALARM_T1T2_NOSENSOR       246
#define  IDS_ALARM_T1T2_NOCONNECT      247
#define  IDS_ALARM_SPO2_NOSENSOR       248
#define  IDS_ALARM_SPO2_NOPATIENT      249
#define  IDS_ALARM_SPO2_NOPULSE        250
#define  IDS_ALARM_SPO2_RISKPULSE      251
#define  IDS_ALARM_SPO2_RISKSAT        252
#define  IDS_ALARM_SPO2_TUNEPROC       253
#define  IDS_ALARM_SPO2_TUNEERR        254
#define  IDS_ALARM_SPO2_DARKOBJ        255
#define  IDS_ALARM_SPO2_TRANSPOBJ      256
#define  IDS_ALARM_SPO2_BADSIGNAL      257
#define  IDS_ALARM_NIBP_NORESP         258
#define  IDS_ALARM_NIBP_RISKSS         259
#define  IDS_ALARM_NIBP_RISKDD         260
#define  IDS_ALARM_NIBP_RISKCC         261
#define  IDS_ALARM_NIBP_RISKMEASTIME   262
#define  IDS_ALARM_ECG_NOCONNECT       263
#define  IDS_ALARM_ECG_LBREAK          264
#define  IDS_ALARM_ECG_RBREAK          265
#define  IDS_ALARM_ECG_FBREAK          266
#define  IDS_ALARM_ECG_CBREAK          267
#define  IDS_ALARM_ECG_RISKHR          268
#define  IDS_ALARM_ECG_RISKSTI         269
#define  IDS_ALARM_ECG_RISKSTII        270
#define  IDS_ALARM_ECG_RISKSTIII       271
#define  IDS_ALARM_ECG_RISKSTAVR       272
#define  IDS_ALARM_ECG_RISKSTAVL       273
#define  IDS_ALARM_ECG_RISKSTAVF       274
#define  IDS_ALARM_ECG_RISKSTV         275
#define  IDS_ALARM_T1T2_RISKT1         276
#define  IDS_ALARM_T1T2_RISKT2         277
#define  IDS_ALARM_T1T2_RISKDT         278
#define  IDS_ALARM_RESP_RISKBR         279
#define  IDS_ALARM_RESP_APNOE          280
#define  IDS_ALARM_SYS_LOWCHARGE       281
#define  IDS_ALARM_SYS_EXTREMLOWCHARGE 282
#define  IDS_ALARM_ECG_ASYSTOLIA       283
#define  IDS_ALARM_ECG_PM_NO_ANSWER    284
#define  IDS_ALARM_ECG_TACHYCARDIA     285
#define  IDS_ALARM_SPO2_NOCONNECT      286
#define  IDS_ALARM_TPRN_OPENED         287
#define  IDS_ALARM_TPRN_PAPEROUT       288
#define  IDS_ALARM_TPRN_OVERHEAT       289
#define  IDS_ALARM_TPRN_NOCONNECT      290
#define  IDS_APNOE            291
#define  IDS_INVALID_PASSWORD 292
#define  IDS_TRY_AGAIN        293
#define  IDS_ALARM_RESP_BADCONTACT_RL  294
#define  IDS_ALARM_RESP_BADCONTACT_RF  295
#define  IDS_MORE5MODULES_1   296
#define  IDS_MORE5MODULES_2   297
#define  IDS_CO2SET           298
#define  IDS_MORE6MODULES_2   299
#define  IDS_HRSRC            300
#define  IDS_QRSBEEPVOL       301
#define  IDS_ETCO2ALR         302
#define  IDS_ICO2ALR          303
#define  IDS_DRAWCO2          304
#define  IDS_ALARM_CO2_RISKETCO2       305
#define  IDS_ALARM_CO2_RISKICO2        306
#define  IDS_ALARM_CO2_RISKBRCO2       307
#define  IDS_BAR_PRESSURE     308
#define  IDS_ALARM_NIBP_RISKINFL       309
#define  IDS_ALARM_ECG_PM_NO_QRS       310
#define  IDS_ALARM_EXT        311
#define  IDS_ALARM_HA_EXT     312
#define  IDS_ALARM_MA_EXT     313
#define  IDS_ALARM_TA_EXT     314
#define  IDS_COMPLETED        315
#define  IDS_ALARM_NIBP_WEAKSIGNAL     316
#define  IDS_ALARM_NIBP_ERRSIGNAL      317
#define  IDS_ALARM_NIBP_EXCRETRYCOUNT  318
#define  IDS_ALARM_NIBP_PNEUMBLOCK     319
#define  IDS_ALARM_NIBP_INFLTIMEOUT    320
#define  IDS_CABLETYPE        321
#define  IDS_3LEADS           322
#define  IDS_5LEADS           323
#define  IDS_POWERING_OFF     324
#define  IDS_ST_SET           325
#define  IDS_DISPLAYED_ST     326
#define  IDS_RESTARTING       327
#define  IDS_ALARM_NIBP_CALIB_EXPIRED  328
#define  IDS_LAST_CALIBRATED  329
#define  IDS_VERIF_FINISHED   330
#define  IDS_LEAKTEST_FINISHED_OK      331
#define  IDS_LEAKTEST_FINISHED_FAIL    332
#define  IDS_CALIB_FINISHED   333
#define  IDS_J_SHIFT          334
#define  IDS_DIAGNOSTICS_F    335
#define  IDS_ROOM_AIR         336
#define  IDS_N2O              337
#define  IDS_HELIUM           338
#define  IDS_BALANCE_GAS      339
#define  IDS_O2_COMPENS       340
#define  IDS_ANEST_AGENT      341
#define  IDS_ALARM_CO2_INVDATA         342
#define  IDS_BRC                       343
#define  IDS_ETCO2                     344
#define  IDS_ICO2                      345
#define  IDS_DATE                      346
#define  IDS_HOURMIN                   347
#define  IDS_PERCENT                   348
#define  IDS_DEG                       349
#define  IDS_ALARM_CO2_NOCONNECT       350
#define  IDS_ALARM_CO2_OVERTEMP        351
#define  IDS_CO2INISET                 352
#define  IDS_ZEROING                   353
#define  IDS_ALARM_ECG_VENTR_FIBR      354
#define  IDS_ALARM_ECG_VENTR_FLUT      355
#define  IDS_ALARM_CO2_ZEROING         356
#define  IDS_ALARM_NIBP_INVPOWER       357
#define  IDS_OPERATION_IMPOSSIBLE      358
#define  IDS_CHECK_CO2_ADAPTER         359
#define  IDS_ALARM_CO2_CHECKSENSOR     IDS_CHECK_CO2_ADAPTER
#define  IDS_ALARM_CO2_WARMUP          360
#define  IDS_1MIN                      361
#define  IDS_2MIN                      362
#define  IDS_5MIN                      363
#define  IDS_10MIN                     364
#define  IDS_15MIN                     365
#define  IDS_30MIN                     366
#define  IDS_60MIN                     367
#define  IDS_CLEAR_EVENTS              368
#define  IDS_FONT                      369
#define  IDS_SMALL                     370
#define  IDS_NORMAL                    371
#define  IDS_LARGE                     372
#define  IDS_DISP_GRAPH_MODE           373
#define  IDS_MONITOR                   374
#define  IDS_CHARGE_BAT                375
#define  IDS_CLEAR_ALL_ALARMS          376
#define  IDS_DEMO_VIDEO                377
#define  IDS_NO_DATA                   378
#define  IDS_IN_60S                    379
#define  IDS_SIZE                      380
#define  IDS_HASH                      381
#define  IDS_PATIENT_MONITOR           382
#define  IDS_SENSOREX_PM1              383
#define  IDS_INFORMATION               384
#define  IDS_ALARM_SYS_NO_USBDISK      385
#define  IDS_ALARM_CO2_STARTUP         386
#define  IDS_APPLY                     387
#define  IDS_WEIGHT_G                  388
#define  IDS_SCAN_RATE                 389
#define  IDS_ALARM_RESP_BREAK          390
#define  IDS_FILES                     391
#define  IDS_3LEADS_1CHAN              392
#define  IDS_STAGE                     393
#define  IDS_ALARM_SYS_CS_NOCONNECT    394
#define  IDS_ADMINISTRATION            395
#define  IDS_TECH_MENU                 396

#endif // __IDS_H
